<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://acme.org/wsdl" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HelloWorldService" targetNamespace="http://acme.org/wsdl">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://acme.org/wsdl" schemaLocation="HelloWorldService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="helloName">
    <part element="tns:helloName" name="parameters">
    </part>
  </message>
  <message name="helloNameResponse">
    <part element="tns:helloNameResponse" name="parameters">
    </part>
  </message>
  <portType name="HelloWorld">
    <operation name="helloName">
      <input message="tns:helloName" wsam:Action="http://acme.org/wsdl/HelloWorld/helloNameRequest">
    </input>
      <output message="tns:helloNameResponse" wsam:Action="http://acme.org/wsdl/HelloWorld/helloNameResponse">
    </output>
    </operation>
  </portType>
  <binding name="HelloWorldPortBinding" type="tns:HelloWorld">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="helloName">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="HelloWorldService">
    <port binding="tns:HelloWorldPortBinding" name="HelloWorldPort">
      <soap:address location="http://localhost:9081/helloWorld/HelloWorldService"/>
    </port>
  </service>
</definitions>
